import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Card } from "../components/Card";
import { Header } from "../components/Header";
import { Pagination } from "../components/Pagination";
import { SubCard } from "../components/SubCard";
import styles from "../styles/Home.module.css";
import { IBaseList, IPokemon, Pokemon } from "../types";

const Home: NextPage<{ response: IBaseList; page: number }> = ({
  response,
  page,
}) => {
  const [details, setDetails] = useState<Pokemon>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <section className={styles.layout}>
          <div className={styles.cardList}>
            {response?.results?.map((val: IPokemon, ind: number) => {
              return (
                <Card
                  key={`${val.name}${ind}`}
                  name={val.name}
                  url={val.url}
                  onChangeDetails={setDetails}
                />
              );
            })}
          </div>

          {details && (
            <div className={styles.cardDetails}>
              <SubCard details={details} onChangeDetails={setDetails} />
            </div>
          )}
        </section>

        <Pagination
          page={page}
          maxPage={response.count / 16}
          onChangePage={setDetails}
        />
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({
  query: { page = 1 },
}) => {
  let offset = (+page - 1) * 16;

  const res = await fetch(
    `https://pokeapi.co/api/v2/pokemon?offset=${offset}&limit=16`
  );
  const response: IBaseList = await res.json();

  return {
    props: {
      response,
      page: +page,
    },
  };
};

export default Home;
